name: Srikanth Srinivas
bio: 'Postgraduate Bioinformatics student at the University of Bristol | Ex-Research Intern at NIHR Global Health Research Unit Lab'

# If it's an external image, update below for true
external-image: false
picture: 'assets/images/mainimg.png'

url: http://srikanth-srinivas.github.io

permalink: /:title/
theme: jekyll-theme-merlot
markdown: kramdown
highlighter: rouge # other options?

# To enable google analytics, supply your token below
# analytics-google: 'UA-MYANALYTICS'

# To enable piwik tracking, supply your url & site ID below
# analytics-piwik-url: 'piwik.my-host.com'
# analytics-piwik-id: 1

# If you don't want comments in your posts, set to false
disqus: false

# Social Media
linkedin: 'https://linkedin.com/in/srikanth-srinivas-4a6047224'
github: 'https://github.com/srikanth-srinvas'
email: 'srikanth.srinivas.2024@bristol.ac.uk'

# Do you want a larger site? Change the option below
width: large

# If you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

# If you don't need projects, comment the *projects* configs below
# if you don't need "about" or "blog", comment them out below
# likewise, comment out lists, research, or bookshelf pages
about: true
blog: false
cv: true
projects: true
modalities: false
maverick: false
research: false
bookshelf: false

# Do you want to show the "read time" of the posts?
read-time: true

# Do you want to show the "tags" inside the posts?
show-tags: true

# Related posts inside a post?
related: true

# Do you want some animations?
animation: true

gems:
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

jekyll-mentions:
  base_url: 'https://github.com'

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - gulpfile.js
  - package.json
  - _site
  - src
  - vendor
  - CNAME
  - indigo-gh-pages.zip
  - Rakefile
  - travis.sh